name: Render & Deploy R Markdown

on:
  push:
    branches: [main, master]

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            rmarkdown
            knitr
            bookdown   # ← remove this comment or move it outside the literal!

      - name: Render R Markdown
        run: Rscript -e 'rmarkdown::render("codas-test.Rmd")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
