name: Render and Deploy Bookdown

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write
  actions: read

jobs:
  build-bookdown:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up R
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      # Step 2.5: Install system dependencies (new step)
      # pak::pkg_sysreqs(unique_packages,sysreqs_platform = "ubuntu")
      - name: Install system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
          make \
          libgdal-dev \
          gdal-bin \
          libgeos-dev \
          libproj-dev \
          libsqlite3-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libssl-dev \
          libsecret-1-dev \
          libsodium-dev \
          libicu-dev \
          libudunits2-dev \
          libpng-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          zlib1g-dev \
          libjpeg-dev \
          libtiff-dev \
          libfribidi-dev \
          libharfbuzz-dev \
          rustc \
          cargo \
          libmagick++-dev
      
      # Step 3: Set up Pandoc
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1

      # Step 5: Render rmarkdown
      - name: Render Bookdown
        run: R -e 'rmarkdown::render("codas-test.Rmd", "all")'

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
