name: Render & Deploy R Markdown

on:
  push:
    branches: [main, master]

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1 · Checkout source
      - uses: actions/checkout@v3

      # 2 · Set up R (includes pandoc on Ubuntu runners)
      - uses: r-lib/actions/setup-r@v2

      # 3 · Install just the R packages your doc needs
      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            rmarkdown    # add others as you need

      # 4 · Render the document (change the file name as required)
      - name: Render R Markdown
        run: Rscript -e 'rmarkdown::render("codas-test.Rmd")'

      # 5 · Publish the generated HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
